management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  server:
    port: 9292
  endpoint:
    shutdown:
      enabled: true # ???? ????, ????? ??????
    health:
      show-components: always
      # show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: hello-actuator
    company: yh

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true